### ISSUE TITLE
Retire module

### ISSUE THREAD

**Issue by adamralph** [RaveNoX/ScriptCs.Shebang#1]
@RaveNoX first of all, this is an awesome module and thanks for providing it.

However, from scriptcs 0.14 onwards, this has been built into scriptcs itself (https://github.com/scriptcs/scriptcs/releases/tag/v0.14.0). To save you the trouble of maintaining it going forward and to avoid confusion for users, I wonder if it may be a good idea to retire the module gracefully. Obviously anyone using scriptcs 0.13.x or earlier will still find it useful. One of the drivers behind this is that we are going to be introducing a major breaking change in either 0.15 or 0.16 (the removal of Common.Logging) which will probably break all modules so if users already know that this module is no longer required it could avoid a lot of friction.

I humbly propose an edit to the description on the NuGet Gallery to indicate that the functionality is built into scriptcs 0.14 and later and that the module should not be used with those versions, and an update to README.md in this repo with the same information.

**Comment by RaveNoX** [comment]
Nuget description updated. It will be visible as soon as nuget site refresh the package.

**Comment by adamralph** [comment]
Thanks very much, and thanks again for providing this module.
